ModelMonitoring:
    monitoringScheduleName: human-pose-prediction-monitoring-schdule
    threshold: "1.0"
    monitoringImageName: human-pose-prediction-monitoring-container
    baseJobName: human-pose-prediction-monitoring-job
    processingOutput:
        s3DestinationPrefix: endpoint/monitoring_schedule
        outputName: result
        mlDefaultResultSource: /opt/ml/processing/resultdata

EndpointConfig:
    modelName: human-pose-prediction-model
    endpointConfigName: human-pose-prediction-config
    endpointName: human-pose-prediction-endpoint
    roleArn: arn:aws:iam::525419040953:role/CloudOps

Instance:
    instanceType: ml.m5.xlarge
    instanceCount: 1

InferenceConfig:
    ecrInferenceImageName: human-pose-inferencing-container

DataCapture:
    initialSamplingPercentage: 100
    enableCapture: True

S3Config:
    bucketName: mlops-pipeline-human-pose-estimation
    inputDir: inputdata/
    s3Prefix: human-pose/
    realtimeS3Prefix: realtime/
    outputDir: prediction/
    modelDir: model/
    dataCapture: endpoint/data_capture
    tensors: endpoint/tensors
